package nut.model;

import nut.model.Goal;
import nut.model.ValidationException;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

public class Build 
implements java.io.Serializable
{
    //--------------------------/
    //- Class/Member Variables -/
    //--------------------------/

    /**
     * The directory where all files generated by the build are
     * placed.
     */
    private String directory = "target";

    /**
     * The directory where is nut.xml
     */
    private String baseDirectory = ".";

    /**
     * This element specifies a directory containing the source of
     * the project. The
     * generated build system will compile the source
     * in this directory when the project is
     * built. The path given is relative to the project
     * descriptor.
     */
    private String sourceDirectory = "src/java";

    /**
     * This element specifies a directory containing the unit test
     * source of the
     * project. The generated build system will compile
     * these directories when the project is
     * being tested. The path given is relative to the
     * project descriptor.
     */
    private String testSourceDirectory = "test/java";

    /**
     * The testng suite filename.
     */
    private String testSuiteFile = "test/testng.xml";

    /**
     * The directory where compiled application classes are placed.
     */
    private String outputDirectory = "target/classes";

    /**
     * The directory where compiled test classes are placed.
     */
    private String testOutputDirectory = "target/test-classes";

    /**
     * The directory where test reports are placed.
     */
    private String testReportDirectory = "target/test-reports";

    /**
     * Field goals.
     */
    private List<Goal> goals;

    /**
     * The current encoding used when reading/writing this model.
     */
    private String modelEncoding = "UTF-8";

    //-----------/
    //- Methods -/
    //-----------/

    public String getDirectory()
    {
        return this.directory;
    }

    public void setDirectory( String directory )
    {
        this.directory = directory;
    }

    public String getBaseDirectory()
    {
        return this.baseDirectory;
    }

    public void setBaseDirectory( String baseDirectory )
    {
        this.baseDirectory = baseDirectory;
    }

    public String getSourceDirectory()
    {
        return this.sourceDirectory;
    }

    public void setSourceDirectory( String sourceDirectory )
    {
        this.sourceDirectory = sourceDirectory;
    }

    public String getTestSourceDirectory()
    {
        return this.testSourceDirectory;
    }

    public void setTestSourceDirectory( String testSourceDirectory )
    {
        this.testSourceDirectory = testSourceDirectory;
    }

    public String getTestSuiteFile()
    {
        return this.testSuiteFile;
    }

    public void setTestSuiteFile( String testSuiteFile )
    {
        this.testSuiteFile = testSuiteFile;
    }

    public String getOutputDirectory()
    {
        return this.outputDirectory;
    }

    public void setOutputDirectory( String outputDirectory )
    {
        this.outputDirectory = outputDirectory;
    }

    public String getTestOutputDirectory()
    {
        return this.testOutputDirectory;
    }

    public void setTestOutputDirectory( String testOutputDirectory )
    {
        this.testOutputDirectory = testOutputDirectory;
    }

    public String getTestReportDirectory()
    {
        return this.testReportDirectory;
    }

    public void setTestReportDirectory( String testReportDirectory )
    {
        this.testReportDirectory = testReportDirectory;
    }

    public List<Goal> getGoals()
    {
        if ( this.goals == null )
        {
            this.goals = new ArrayList<Goal>();
        }
    
        return this.goals;
    }

    public void setGoals( List<Goal> goals )
    {
        this.goals = goals;
    }

    /**
     * The current encoding used when reading/writing this model.
     */
    public String getModelEncoding()
    {
        return modelEncoding;
    }

    public void setModelEncoding( String modelEncoding )
    {
        this.modelEncoding = modelEncoding;
    }

    /**
     * validate method
     */
    public void validate()
        throws ValidationException
    {
        List goals = this.getGoals();
        for ( Iterator it = goals.iterator(); it.hasNext(); )
        {
          Goal goal = (Goal) it.next();
          goal.validate();
        }
    }
}
