#!/bin/sh
set -e

cd $(dirname $0)
root=$(pwd)
NUT_VERSION="3.0"
NUT_HOME="$HOME/nutRepository"

echo "Build nut script"
cat <<EOF >nut
#!/bin/bash
# Nut start up script
# ----------------------------------------------------------------------------
export NUT_VERSION=$NUT_VERSION
export NUT_HOME=$NUT_HOME
java -Xmx512M -classpath \$NUT_HOME/nut/nut-\$NUT_VERSION.jar:\$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar:\$NUT_HOME/com/beust/jcommander-1.48.jar:\$NUT_HOME/org/testng/testng-6.8.7.jar nut.Nut "-Dversion=\$NUT_VERSION" "-Dhome=\$NUT_HOME" \$*
EOF

chmod +x nut
#sudo install nut /usr/bin/

echo "Build nut local repository"
[ -d $NUT_HOME ] && rm -r $NUT_HOME
mkdir -p $NUT_HOME/nut
rm -rf localRepository/*~
cp -a localRepository/* $NUT_HOME/

cd $root
mkdir -p target/classes
echo "Compiling.."
options="-d $root/target/classes -cp $root/target/classes:$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar:$NUT_HOME/org/testng/testng-6.8.7.jar -deprecation -Xlint:unchecked"
echo " - logging"
cd src/main/java/logging
javac $options Log.java
echo " - model"
cd ../model
javac $options Dependency.java Project.java ParserException.java ValidationException.java
echo " - goals"
cd ../goals
javac $options packs/util/CopyFiles.java packs/util/ZipFiles.java
javac $options Goal.java GoalException.java Clean.java Compile.java Install.java Pack.java Test.java Run.java packs/Jar.java packs/War.java packs/Zip.java
echo " - interpolation"
cd ../interpolation
javac $options Interpolator.java
echo " - build"
cd ../build
javac $options DependencyNotFoundException.java DependencyChecker.java DuplicateProjectException.java Scanner.java Sorter.java Builder.java
echo " - Nut"
cd ..
javac $options Nut.java

cd $root
echo "Build Nut.jar"
mkdir -p $NUT_HOME/nut
jar cf $NUT_HOME/nut/nut-$NUT_VERSION.jar -C target/classes .
rm -r target

echo "Install /usr/bin/nut'"
sudo install nut /usr/bin/
rm nut
echo "Done."
