#!/bin/sh
set -e

cd $(dirname $0)
root=$(pwd)
tmp=$(grep -P -m 1 "<version>(.*)</version>" nut.xml)
NUT_VERSION=$(expr $tmp : '<version>\(.*\)</version>')
NUT_HOME="$HOME/nutRepository"

echo "Build nut script"
cat <<EOF >nut
#!/bin/bash
# Nut start up script
# ----------------------------------------------------------------------------
export NUT_VERSION=$NUT_VERSION
export NUT_HOME=$NUT_HOME
java -Xmx512M -classpath ./target/test-classes:\$NUT_HOME/nut/Nut-\$NUT_VERSION.jar:\$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar:\$NUT_HOME/com/beust/jcommander-1.7.jar:\$NUT_HOME/org/testng/testng-6.8.7.jar nut.Nut "-Dversion=\$NUT_VERSION" "-Dhome=\$NUT_HOME" \$*
EOF

sudo install nut /usr/bin/
rm nut

echo "Build nut local repository"
[ -d $NUT_HOME ] && rm -r $NUT_HOME
mkdir -p $NUT_HOME/nut
cp -a localRepository/* $NUT_HOME/

mkdir -p target/classes 

cd $root
echo "Compiling.."
options="-d $root/target/classes -cp $root/target/classes:$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar:$NUT_HOME/org/testng/testng-6.8.7.jar -deprecation -Xlint:unchecked"
cd $root/Nut
echo " - logging"
cd src/java/logging
javac $options Log.java
echo " - xml"
cd ../xml
javac $options XmlPullParserException.java XmlPullParser.java XmlSerializer.java
echo " - artifact"
cd ../artifact
javac $options InvalidArtifactRTException.java Artifact.java
echo " - model"
cd ../model
javac $options Goal.java Dependency.java Build.java Model.java Repository.java xmlReader.java xmlWriter.java ValidationException.java
echo " - project"
cd ../project
javac $options DependencyNotFoundException.java InvalidDependencyVersionException.java DuplicateProjectException.java BuildFailureException.java Project.java ProjectBuilder.java ProjectSorter.java DependencyChecker.java
echo " - goals"
cd ../goals
javac $options Clean.java
javac $options CompileJava.java
javac $options Install.java
javac $options Pack.java
javac $options TestTestNG.java ../testng/TestListener.java
echo " - Nut"
cd ..
javac $options Nut.java

cd $root
echo "Build Nut.jar"
mkdir -p $NUT_HOME/nut
jar cf $NUT_HOME/nut/Nut-$NUT_VERSION.jar -C target/classes .
rm -r target

echo "Build packaging"
mkdir -p $NUT_HOME/nut/packaging
cp packaging/xml/src/resources/xml.xml         $NUT_HOME/nut/packaging/xml-$NUT_VERSION.xml
cp packaging/jar/src/resources/jar.xml         $NUT_HOME/nut/packaging/jar-$NUT_VERSION.xml
cp packaging/war/src/resources/war.xml         $NUT_HOME/nut/packaging/war-$NUT_VERSION.xml
cp packaging/zip/src/resources/zip.xml         $NUT_HOME/nut/packaging/zip-$NUT_VERSION.xml
cp packaging/modules/src/resources/modules.xml $NUT_HOME/nut/packaging/modules-$NUT_VERSION.xml
echo "Done."
