#!/bin/sh
set -e

root=$(pwd)

tmp=$(grep -P "<version>(.*)</version>" nut.xml)
NUT_VERSION=$(expr $tmp : '<version>\(.*\)</version>')
NUT_HOME="$HOME/nutRepository"

echo "Build nut"
cat <<EOF >nut
#!/bin/bash
# Nut start up script
# ----------------------------------------------------------------------------
export NUT_VERSION=$NUT_VERSION
export NUT_HOME=$NUT_HOME
java -Xmx512M -classpath \$NUT_HOME/nut/core/Nut-\$NUT_VERSION.jar:\$NUT_HOME/nut/logging/Log-\$NUT_VERSION.jar:\$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar:\$NUT_HOME/com/beust/jcommander-1.7.jar:\$NUT_HOME/org/testng/testng-6.8.7.jar nut.Nut "-Dversion=\$NUT_VERSION" "-Dhome=\$NUT_HOME" \$*
EOF

chmod +x nut
sudo mv nut /usr/bin/

echo "Build repository"
[ -d $NUT_HOME ] && rm -r $NUT_HOME
mkdir -p $NUT_HOME/nut
cp -a localRepository/* $NUT_HOME/

mkdir -p target/classes 

echo "Build log"
options="-d $root/target/classes -cp $root/target/classes:$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar -deprecation -Xlint:unchecked"
cd logging/src/java
javac $options Log.java

cd $root
mkdir -p $NUT_HOME/nut/logging
jar cf $NUT_HOME/nut/logging/Log-$NUT_VERSION.jar -C target/classes .

echo "Build core"
options="-d $root/target/classes -cp $root/target/classes:$NUT_HOME/nut/logging/Log-$NUT_VERSION.jar:$NUT_HOME/org/codehaus/plexus/plexus-utils-3.0.jar -deprecation -Xlint:unchecked"
cd $root
cd core/src/java/xml/
javac $options XmlPullParserException.java XmlPullParser.java XmlSerializer.java
cd ../artifact
javac $options InvalidArtifactRTException.java Artifact.java
cd ../model
javac $options Plugin.java PluginContainer.java Dependency.java Build.java Model.java xmlReader.java xmlWriter.java EffectiveModel.java 
cd ../project/validation
javac $options ModelValidationException.java ModelValidator.java 
cd ..
javac $options InvalidDependencyVersionException.java InvalidProjectModelException.java DuplicateProjectException.java NutProject.java ProjectBuildingException.java ProjectBuilder.java ProjectSorter.java
cd ../execution
javac $options BuildFailureException.java ExecutionException.java NutClassRealm.java NutClassLoader.java PluginManager.java 
cd ..
javac $options Nut.java

cd $root
mkdir -p $NUT_HOME/nut/core
jar cf $NUT_HOME/nut/core/Nut-$NUT_VERSION.jar -C target/classes .

echo "Build plugins"
cd $root
mkdir -p $NUT_HOME/nut/plugins

options="-d target/classes -cp target/classes:$NUT_HOME/nut/logging/Log-$NUT_VERSION.jar:$NUT_HOME/nut/core/Nut-$NUT_VERSION.jar -deprecation -Xlint:unchecked"
rm -r target/classes/*
javac $options plugins/cleaner/src/java/cleaner.java
jar cf $NUT_HOME/nut/plugins/cleaner-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
javac $options plugins/installer/src/java/installer.java
jar cf $NUT_HOME/nut/plugins/installer-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
javac $options plugins/depProcessor/src/java/depProcessor.java
jar cf $NUT_HOME/nut/plugins/depProcessor-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
javac $options plugins/javaArchiver/src/java/javaArchiver.java
jar cf $NUT_HOME/nut/plugins/javaArchiver-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
javac $options plugins/javaCompiler/src/java/javaCompiler.java
jar cf $NUT_HOME/nut/plugins/javaCompiler-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
javac $options plugins/release/src/java/release.java
jar cf $NUT_HOME/nut/plugins/release-$NUT_VERSION.jar -C target/classes .

rm -r target/classes/*
options="-d target/classes -cp target/classes:$NUT_HOME/nut/logging/Log-$NUT_VERSION.jar:$NUT_HOME/nut/core/Nut-$NUT_VERSION.jar:$NUT_HOME/org/testng/testng-6.8.7.jar -deprecation -Xlint:unchecked"
javac $options plugins/testRunner/src/java/testRunner.java plugins/testRunner/src/java/TestListener.java
jar cf $NUT_HOME/nut/plugins/testRunner-$NUT_VERSION.jar -C target/classes .

echo "Build packaging"
mkdir -p $NUT_HOME/nut/packaging
cp packaging/xml/src/resources/xml.xml     $NUT_HOME/nut/packaging/xml-$NUT_VERSION.xml
cp packaging/jar/src/resources/jar.xml     $NUT_HOME/nut/packaging/jar-$NUT_VERSION.xml
cp packaging/war/src/resources/war.xml     $NUT_HOME/nut/packaging/war-$NUT_VERSION.xml
cp packaging/modules/src/resources/modules.xml $NUT_HOME/nut/packaging/modules-$NUT_VERSION.xml

rm -r target
